apiVersion: v1
kind: Service
metadata:
  name: webapp-deployment-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/surajmohanm/webapp-tekton:latest
        ports:
        - containerPort: 80
